/*
 * STOPCServerUnregistry.java
 *
 * Created on __DATE__, __TIME__
 */

package stopcserver;

import javax.swing.JOptionPane;

import com.st.opcserver.dll.STOPCServer;

/**
 *
 * @author  __USER__
 */
public class STOPCServerUnregistry extends javax.swing.JFrame {

	STOPCServer sos = new STOPCServer();
	/** Creates new form STOPCServerUnregistry */
	public STOPCServerUnregistry() {
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		OK = new javax.swing.JButton();
		Cancel = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("\u5378\u8f7d\u670d\u52a1\u5668");

		jLabel1.setIcon(new javax.swing.ImageIcon("D:\\java\\workspace\\stopcserver\\icon\\serverunregistry.png")); // NOI18N

		OK.setText("\u518d\u6b21\u786e\u8ba4");
		OK.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				OKActionPerformed(evt);
			}
		});

		Cancel.setText("\u53d6\u6d88\u5378\u8f7d");
		Cancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CancelActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(47, 47, 47)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup()
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1).addGap(30, 30, 30))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(Cancel, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(OK, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 127,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(62, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(32, 32, 32).addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(OK)
						.addGap(22, 22, 22).addComponent(Cancel).addContainerGap(53, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
		//GEN-END:initComponents

	private void CancelActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	private void OKActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if(sos.unregisterServer(STOPCServerSimulator.servername)){
			JOptionPane.showMessageDialog(null, "卸载服务器成功！", "卸载服务器", JOptionPane.INFORMATION_MESSAGE);
			this.dispose();
		}
		else
			JOptionPane.showMessageDialog(null, "卸载服务器失败！\r\n注意检查管理员权限", "卸载服务器", JOptionPane.ERROR_MESSAGE);
	}

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new STOPCServerUnregistry().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton Cancel;
	private javax.swing.JButton OK;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables

}