/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_st_opcserver_dll_STOPCServer */

#ifndef _Included_com_st_opcserver_dll_STOPCServer
#define _Included_com_st_opcserver_dll_STOPCServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    OPCsvrRevision
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_st_opcserver_dll_STOPCServer_OPCsvrRevision
  (JNIEnv *, jobject);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    RegistryServer
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_st_opcserver_dll_STOPCServer_RegistryServer
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    UnregisterServer
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_st_opcserver_dll_STOPCServer_UnregisterServer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    InitServer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_st_opcserver_dll_STOPCServer_InitServer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    UninitServer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_st_opcserver_dll_STOPCServer_UninitServer
  (JNIEnv *, jobject);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    ResetServerRate
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_st_opcserver_dll_STOPCServer_ResetServerRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    NumbrClientConnections
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_st_opcserver_dll_STOPCServer_NumbrClientConnections
  (JNIEnv *, jobject);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    RequestDisconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_st_opcserver_dll_STOPCServer_RequestDisconnect
  (JNIEnv *, jobject);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    RefreshAllClients
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_st_opcserver_dll_STOPCServer_RefreshAllClients
  (JNIEnv *, jobject);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    SetTagNameQualifier
 * Signature: (C)C
 */
JNIEXPORT jchar JNICALL Java_com_st_opcserver_dll_STOPCServer_SetTagNameQualifier
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    SetTagProperties
 * Signature: (JJLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_st_opcserver_dll_STOPCServer_SetTagProperties
  (JNIEnv *, jobject, jlong, jlong, jstring, jstring);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    DeleteTag
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_st_opcserver_dll_STOPCServer_DeleteTag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    AddTag
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_com_st_opcserver_dll_STOPCServer_AddTag
  (JNIEnv *, jobject, jstring, jstring, jstring, jboolean);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    UpdateTag
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_st_opcserver_dll_STOPCServer_UpdateTag
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    UpdateTagByName
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_st_opcserver_dll_STOPCServer_UpdateTagByName
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    ReadTag
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_st_opcserver_dll_STOPCServer_ReadTag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    AllAddTag
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JJ[F[J[Z)J
 */
JNIEXPORT jlong JNICALL Java_com_st_opcserver_dll_STOPCServer_AllAddTag
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jlong, jlong, jfloatArray, jlongArray, jbooleanArray);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    AllUpdateTag
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[F[J[Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_st_opcserver_dll_STOPCServer_AllUpdateTag
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jfloatArray, jlongArray, jbooleanArray);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    StartUpdateTags
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_st_opcserver_dll_STOPCServer_StartUpdateTags
  (JNIEnv *, jobject);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    UpdateTagToList
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_st_opcserver_dll_STOPCServer_UpdateTagToList
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    EndUpdateTags
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_st_opcserver_dll_STOPCServer_EndUpdateTags
  (JNIEnv *, jobject);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    SetItemLevelAlarm
 * Signature: (JIFJZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_st_opcserver_dll_STOPCServer_SetItemLevelAlarm
  (JNIEnv *, jobject, jlong, jint, jfloat, jlong, jboolean);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    GetItemLevelAlarm
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_st_opcserver_dll_STOPCServer_GetItemLevelAlarm
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_st_opcserver_dll_STOPCServer
 * Method:    SuspendTagUpdates
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_st_opcserver_dll_STOPCServer_SuspendTagUpdates
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
