/*
 * STOPCServerRegistryInit.java
 *
 * Created on __DATE__, __TIME__
 */

package stopcserver;
import javax.swing.JOptionPane;

import com.st.opcserver.dll.STOPCServer;
/**
 *
 * @author  __USER__
 */
public class STOPCServerRegistryInit extends javax.swing.JFrame {

	
	STOPCServer sos = new STOPCServer();
	/** Creates new form STOPCServerRegistryInit */
	public STOPCServerRegistryInit() {
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		ServerName = new javax.swing.JTextField();
		ServerDescription = new javax.swing.JTextField();
		OK = new javax.swing.JButton();
		Cancel = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		ServerRate = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("\u6ce8\u518c\u548c\u521d\u59cb\u5316\u670d\u52a1\u5668");

		jLabel1.setIcon(new javax.swing.ImageIcon("D:\\java\\workspace\\stopcserver\\icon\\servername.png")); // NOI18N
		jLabel1.setText("\u670d\u52a1\u5668\u540d\u5b57:");

		jLabel2.setIcon(new javax.swing.ImageIcon("D:\\java\\workspace\\stopcserver\\icon\\serverdescription.png")); // NOI18N
		jLabel2.setText("\u670d\u52a1\u5668\u63cf\u8ff0:");

		OK.setText("\u786e\u5b9a");
		OK.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				OKActionPerformed(evt);
			}
		});

		Cancel.setText("\u53d6\u6d88");
		Cancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CancelActionPerformed(evt);
			}
		});

		jLabel3.setIcon(new javax.swing.ImageIcon("D:\\java\\workspace\\stopcserver\\icon\\serverrate.png")); // NOI18N
		jLabel3.setText("\u670d\u52a1\u5668\u66f4\u65b0\u901f\u5ea6:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(40, 40, 40)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel1)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel3)
												.addGroup(layout.createSequentialGroup().addComponent(jLabel2)
														.addGap(24, 24, 24))))
								.addGap(36, 36, 36).addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(layout.createSequentialGroup()
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(ServerName, javax.swing.GroupLayout.DEFAULT_SIZE,
																96, Short.MAX_VALUE))
												.addComponent(ServerDescription).addComponent(ServerRate)))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addGap(18, 18, 18).addComponent(OK)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88,
												Short.MAX_VALUE)
										.addComponent(Cancel).addGap(27, 27, 27)))
				.addGap(39, 39, 39)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(35, 35, 35)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(ServerName, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(27, 27, 27)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel2)
						.addComponent(ServerDescription, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(27, 27, 27)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3)
						.addComponent(ServerRate, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(42, 42, 42).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(Cancel).addComponent(OK)).addContainerGap(41, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
		//GEN-END:initComponents

	private void CancelActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	private void OKActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if(sos.registryServer(ServerName.getText(), ServerDescription.getText())){//注册成功
			if(sos.initServer(Integer.parseInt(ServerRate.getText()))){			//初始化成功
				STOPCServerSimulator.servername = ServerName.getText();			//保存服务器名字
				JOptionPane.showMessageDialog(null, "注册与初始化服务器成功！", "注册初始化服务器", JOptionPane.INFORMATION_MESSAGE);
				this.dispose();
			}
			else{
				JOptionPane.showMessageDialog(null, "注册成功！初始化失败！\r\n注意检查管理员权限", "注册初始化服务器", JOptionPane.ERROR_MESSAGE);
			}
		}
		else{
			JOptionPane.showMessageDialog(null, "注册失败！\r\n注意检查管理员权限", "注册初始化服务器", JOptionPane.ERROR_MESSAGE);
		}
	}

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new STOPCServerRegistryInit().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton Cancel;
	private javax.swing.JButton OK;
	private javax.swing.JTextField ServerDescription;
	private javax.swing.JTextField ServerName;
	private javax.swing.JTextField ServerRate;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	// End of variables declaration//GEN-END:variables

}